version: "3.8"
services:

    backend:
        image: 2033109/backend:latest
        ports:
        - target: 9966
          published: 9966
          protocol: tcp

    frontend:
        build: ./spring-petclinic-angular/
        image: 2033109/frontend:latest
        ports:
        - target: 8080
          published: 8083
          protocol: tcp
