version: "3.3"

services:

  nginx:
    image: nginx:latest
    build: kubernetes/nginx
    ports:
      - 80:80
    container_name: nginx
    
  backend:
    image: springcommunity/spring-petclinic-rest:latest
    build: spring-petclinic-rest
    ports:
      - 9966:9966
    container_name: backend

  frontend:
    image: springcommunity/spring-petclinic-angular:latest
    build: spring-petclinic-angular
    ports:
      - 8080:8080
    container_name: frontend
