apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  containers:
  - name: backend
    image: springcommunity/spring-petclinic-rest:latest
    ports:
    - containerPort: 9966
  type: ClusterIP

---
apiVersion: app/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  containers:
  - name: backend
    image: springcommunity/spring-petclinic-rest:latest
    ports:
    - containerPort: 9966
  type: ClusterIP
