apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  selector:
      app: frontend
      ports:
      - port: 8080
        targetPort: 8080
        protocol: TCP
      type: ClusterIP
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: backend
          image: springcommunity/spring-petclinic-rest:latest
          ports:
            - containerPort: 9966
          
