apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    selector:
      app: frontend
      ports:
      - port: 8080
        targetPort: 8080
        protocol: TCP
      type: ClusterIP
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: frontend
          image: springcommunity/spring-petclinic-angular:latest
          ports:
            - containerPort: 8080
            
