apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
      - name: frontend
        image: springcommunity/spring-petclinic-angular:latest
        ports:
        - containerPort: 8080
      type: ClusterIP