apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  containers:
  - name: backend
    image: springcommunity/spring-petclinic-angular:latest
    ports:
    - containerPort: 8080
  type: ClusterIP

---
apiVersion: app/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  containers:
  - name: frontend
    image: springcommunity/spring-petclinic-angular:latest
    ports:
    - containerPort: 8080
  type: ClusterIP