apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    app: frontend
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: frontend
          image: springcommunity/spring-petclinic-angular:latest
          ports:
            - containerPort: 8080
                ports:
                  targetPort: 8080
                  protocol: TCP
                type: ClusterIP
